# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_recommend',
        ),
    ]
