# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180301_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
    ]
